export interface VimCommand {
  key: string;
  desc: string;
  category: "movement" | "editing" | "clipboard" | "search_replace" | "advanced";
  subcategory?: string;
  keywords: string[];
}

export const CHEATSHEET_DATA: VimCommand[] = [
  // MOVEMENT - Vertical / Directional
  { key: "gg", desc: "Jump to first line of the file", category: "movement", subcategory: "Vertical", keywords: ["first", "line", "start", "top", "go"] },
  { key: "G", desc: "Jump to end of file", category: "movement", subcategory: "Vertical", keywords: ["end", "file", "bottom", "go", "last"] },
  { key: "H", desc: "Move cursor to top of screen (High)", category: "movement", subcategory: "Vertical", keywords: ["top", "screen", "high", "head"] },
  { key: "M", desc: "Move cursor to middle of screen (Middle)", category: "movement", subcategory: "Vertical", keywords: ["middle", "screen", "center"] },
  { key: "L", desc: "Move cursor to bottom of screen (Low)", category: "movement", subcategory: "Vertical", keywords: ["bottom", "screen", "low"] },
  { key: "{", desc: "Jump to beginning of paragraph / block backward", category: "movement", subcategory: "Vertical", keywords: ["beginning", "paragraph", "block", "backward", "prev"] },
  { key: "}", desc: "Jump to end of paragraph / block forward", category: "movement", subcategory: "Vertical", keywords: ["end", "paragraph", "block", "forward", "next"] },
  { key: "(", desc: "Jump to beginning of sentence backward", category: "movement", subcategory: "Vertical", keywords: ["beginning", "sentence", "backward", "prev"] },
  { key: ")", desc: "Jump to end of sentence forward", category: "movement", subcategory: "Vertical", keywords: ["end", "sentence", "forward", "next"] },
  { key: "#G", desc: "Go to line number # (e.g. 42G)", category: "movement", subcategory: "Vertical", keywords: ["go", "line", "number", "jump"] },
  { key: "*", desc: "Search forward for word under cursor", category: "movement", subcategory: "Vertical", keywords: ["search", "word", "cursor", "find", "next"] },
  { key: "#", desc: "Search backward for word under cursor", category: "movement", subcategory: "Vertical", keywords: ["search", "word", "cursor", "find", "prev"] },
  { key: "n", desc: "Repeat last search in same direction", category: "movement", subcategory: "Vertical", keywords: ["repeat", "search", "next", "direction"] },
  { key: "N", desc: "Repeat last search in opposite direction", category: "movement", subcategory: "Vertical", keywords: ["repeat", "search", "opposite", "prev", "direction"] },

  // MOVEMENT - Horizontal
  { key: "0", desc: "Move to hard beginning of current line", category: "movement", subcategory: "Horizontal", keywords: ["start", "beginning", "line", "hard", "zero"] },
  { key: "^", desc: "Move to soft beginning of line (first non-blank char)", category: "movement", subcategory: "Horizontal", keywords: ["start", "beginning", "line", "soft", "first"] },
  { key: "$", desc: "Move to hard end of current line", category: "movement", subcategory: "Horizontal", keywords: ["end", "line", "dollar", "last"] },
  { key: "w", desc: "Move forward to beginning of next word", category: "movement", subcategory: "Horizontal", keywords: ["word", "forward", "next", "start"] },
  { key: "W", desc: "Move forward to beginning of next word (unlimited/whitespace)", category: "movement", subcategory: "Horizontal", keywords: ["word", "forward", "whitespace", "next"] },
  { key: "e", desc: "Move forward to end of current word", category: "movement", subcategory: "Horizontal", keywords: ["word", "forward", "end"] },
  { key: "E", desc: "Move forward to end of current word (unlimited/whitespace)", category: "movement", subcategory: "Horizontal", keywords: ["word", "forward", "end", "whitespace"] },
  { key: "b", desc: "Move backward to beginning of word", category: "movement", subcategory: "Horizontal", keywords: ["word", "backward", "back", "start"] },
  { key: "B", desc: "Move backward to beginning of word (unlimited/whitespace)", category: "movement", subcategory: "Horizontal", keywords: ["word", "backward", "back", "whitespace"] },
  { key: "ge", desc: "Move backward to end of word", category: "movement", subcategory: "Horizontal", keywords: ["word", "backward", "end"] },
  { key: "gE", desc: "Move backward to end of word (unlimited/whitespace)", category: "movement", subcategory: "Horizontal", keywords: ["word", "backward", "end", "whitespace"] },
  { key: "f", desc: "Find character forward (inclusive)", category: "movement", subcategory: "Horizontal", keywords: ["find", "character", "forward", "inclusive", "search"] },
  { key: "F", desc: "Find character backward (inclusive)", category: "movement", subcategory: "Horizontal", keywords: ["find", "character", "backward", "inclusive", "search"] },
  { key: "t", desc: "Find character forward till (stop before)", category: "movement", subcategory: "Horizontal", keywords: ["find", "character", "forward", "till", "before"] },
  { key: "T", desc: "Find character backward till (stop before)", category: "movement", subcategory: "Horizontal", keywords: ["find", "character", "backward", "till", "before"] },
  { key: ";", desc: "Repeat last find command (f, F, t, T)", category: "movement", subcategory: "Horizontal", keywords: ["repeat", "find", "next"] },
  { key: ",", desc: "Repeat last find command in opposite direction", category: "movement", subcategory: "Horizontal", keywords: ["repeat", "find", "opposite", "prev"] },
  { key: "%", desc: "Jump to matching bracket (parenthesis, curly, square)", category: "movement", subcategory: "Horizontal", keywords: ["jump", "matching", "bracket", "parenthesis", "brace"] },
  { key: "<", desc: "Indent line left / shift left", category: "movement", subcategory: "Horizontal", keywords: ["indent", "left", "shift", "format"] },
  { key: ">", desc: "Indent line right / shift right", category: "movement", subcategory: "Horizontal", keywords: ["indent", "right", "shift", "format"] },

  // MOVEMENT - Screen Movement / Scroll
  { key: "zz", desc: "Center screen on cursor line", category: "movement", subcategory: "Screen Scroll", keywords: ["center", "screen", "scroll", "cursor", "view"] },
  { key: "zt", desc: "Scroll cursor line to top of screen", category: "movement", subcategory: "Screen Scroll", keywords: ["top", "screen", "scroll", "cursor", "view"] },
  { key: "zb", desc: "Scroll cursor line to bottom of screen", category: "movement", subcategory: "Screen Scroll", keywords: ["bottom", "screen", "scroll", "cursor", "view"] },
  { key: "Ctrl + e", desc: "Scroll screen down by 1 line", category: "movement", subcategory: "Screen Scroll", keywords: ["scroll", "down", "line", "ctrl-e", "view"] },
  { key: "Ctrl + y", desc: "Scroll screen up by 1 line", category: "movement", subcategory: "Screen Scroll", keywords: ["scroll", "up", "line", "ctrl-y", "view"] },
  { key: "Ctrl + d", desc: "Scroll screen down by half a page", category: "movement", subcategory: "Screen Scroll", keywords: ["scroll", "down", "half", "page", "ctrl-d"] },
  { key: "Ctrl + u", desc: "Scroll screen up by half a page", category: "movement", subcategory: "Screen Scroll", keywords: ["scroll", "up", "half", "page", "ctrl-u"] },
  { key: "Ctrl + f", desc: "Scroll screen down by full page", category: "movement", subcategory: "Screen Scroll", keywords: ["scroll", "down", "full", "page", "ctrl-f"] },
  { key: "Ctrl + b", desc: "Scroll screen up by full page", category: "movement", subcategory: "Screen Scroll", keywords: ["scroll", "up", "full", "page", "ctrl-b"] },

  // EDITING
  { key: "r", desc: "Replace a single character under cursor", category: "editing", subcategory: "Insert/Replace", keywords: ["replace", "character", "change"] },
  { key: "R", desc: "Enter REPLACE mode", category: "editing", subcategory: "Insert/Replace", keywords: ["replace", "mode", "overwrite"] },
  { key: "i", desc: "Enter Insert mode before cursor", category: "editing", subcategory: "Insert/Replace", keywords: ["insert", "mode", "before", "write"] },
  { key: "I", desc: "Enter Insert mode at beginning of line", category: "editing", subcategory: "Insert/Replace", keywords: ["insert", "mode", "beginning", "line", "start"] },
  { key: "a", desc: "Enter Insert mode after cursor (append)", category: "editing", subcategory: "Insert/Replace", keywords: ["append", "insert", "after", "mode"] },
  { key: "A", desc: "Enter Insert mode at end of line (append)", category: "editing", subcategory: "Insert/Replace", keywords: ["append", "insert", "end", "line", "mode"] },
  { key: "o", desc: "Open new line below and insert", category: "editing", subcategory: "Insert/Replace", keywords: ["new", "line", "below", "insert", "open"] },
  { key: "O", desc: "Open new line above and insert", category: "editing", subcategory: "Insert/Replace", keywords: ["new", "line", "above", "insert", "open"] },
  { key: "ea", desc: "Append at the end of the word", category: "editing", subcategory: "Insert/Replace", keywords: ["append", "end", "word", "insert"] },
  { key: "#gI", desc: "Insert text # times (e.g. 5gI)", category: "editing", subcategory: "Insert/Replace", keywords: ["insert", "multiple", "times", "repeat"] },
  { key: "J", desc: "Join line below to current with single space", category: "editing", subcategory: "Lines", keywords: ["join", "line", "combine", "merge"] },
  { key: "gJ", desc: "Join line below to current with NO spaces", category: "editing", subcategory: "Lines", keywords: ["join", "line", "combine", "merge", "no", "spaces"] },
  { key: "cc", desc: "Change entire line (clears line and inserts)", category: "editing", subcategory: "Changes", keywords: ["change", "line", "entire", "replace", "insert"] },
  { key: "C", desc: "Change to the end of the line", category: "editing", subcategory: "Changes", keywords: ["change", "end", "line", "replace"] },
  { key: "ciw", desc: "Change inner word (deletes word, inserts)", category: "editing", subcategory: "Changes", keywords: ["change", "inner", "word", "replace", "delete"] },
  { key: "cm", desc: "Change with motion (e.g. cw, c3w)", category: "editing", subcategory: "Changes", keywords: ["change", "motion", "modifier"] },
  { key: "s", desc: "Delete character and substitute text", category: "editing", subcategory: "Changes", keywords: ["delete", "character", "substitute", "replace", "insert"] },
  { key: "S", desc: "Delete current line and substitute text", category: "editing", subcategory: "Changes", keywords: ["delete", "line", "substitute", "replace", "insert"] },
  { key: "xp", desc: "Transpose two letters (swaps char under cursor and next)", category: "editing", subcategory: "Changes", keywords: ["transpose", "swap", "letters", "characters", "fix"] },
  { key: "u", desc: "Undo last change", category: "editing", subcategory: "History", keywords: ["undo", "history", "back", "revert"] },
  { key: "Ctrl + r", desc: "Redo last undone change", category: "editing", subcategory: "History", keywords: ["redo", "history", "forward", "revert", "ctrl-r"] },
  { key: ".", desc: "Repeat last editing command", category: "editing", subcategory: "History", keywords: ["repeat", "dot", "command", "again"] },
  { key: "~", desc: "Switch character case (upper <-> lower) and move forward", category: "editing", subcategory: "Case", keywords: ["case", "switch", "toggle", "uppercase", "lowercase"] },
  { key: "VU/u", desc: "Make current line uppercase (VU) or lowercase (Vu)", category: "editing", subcategory: "Case", keywords: ["case", "uppercase", "lowercase", "line"] },
  { key: "vEU/u", desc: "Make word uppercase (vEu) or lowercase (vEu)", category: "editing", subcategory: "Case", keywords: ["case", "uppercase", "lowercase", "word"] },

  // CLIPBOARD (CUT & PASTE)
  { key: "yy or Y", desc: "Yank (copy) current line", category: "clipboard", subcategory: "Copy (Yank)", keywords: ["copy", "yank", "line"] },
  { key: "#Y", desc: "Yank (copy) # lines", category: "clipboard", subcategory: "Copy (Yank)", keywords: ["copy", "yank", "lines", "multiple"] },
  { key: "yw", desc: "Yank from cursor to start of next word", category: "clipboard", subcategory: "Copy (Yank)", keywords: ["copy", "yank", "word"] },
  { key: "y#m", desc: "Yank # lines with m movement (e.g. y3j)", category: "clipboard", subcategory: "Copy (Yank)", keywords: ["copy", "yank", "movement", "lines"] },
  { key: "\"ayy", desc: "Yank current line into named register 'a'", category: "clipboard", subcategory: "Registers", keywords: ["copy", "yank", "register", "named"] },
  { key: "p", desc: "Paste (put) clipboard contents AFTER cursor", category: "clipboard", subcategory: "Paste (Put)", keywords: ["paste", "put", "after", "clipboard"] },
  { key: "P", desc: "Paste (put) clipboard contents BEFORE cursor", category: "clipboard", subcategory: "Paste (Put)", keywords: ["paste", "put", "before", "clipboard"] },
  { key: "\"aP", desc: "Paste (put) contents of register 'a' before cursor", category: "clipboard", subcategory: "Registers", keywords: ["paste", "put", "register", "named"] },
  { key: "dd", desc: "Delete (cut) current line", category: "clipboard", subcategory: "Delete (Cut)", keywords: ["delete", "cut", "line"] },
  { key: "#dd", desc: "Delete (cut) # lines downward", category: "clipboard", subcategory: "Delete (Cut)", keywords: ["delete", "cut", "lines", "multiple"] },
  { key: "#dm", desc: "Delete # lines with movement (e.g. d2j)", category: "clipboard", subcategory: "Delete (Cut)", keywords: ["delete", "cut", "movement", "lines"] },
  { key: "D", desc: "Delete (cut) from cursor to end of line", category: "clipboard", subcategory: "Delete (Cut)", keywords: ["delete", "cut", "end", "line"] },
  { key: "dw", desc: "Delete (cut) until beginning of next word", category: "clipboard", subcategory: "Delete (Cut)", keywords: ["delete", "cut", "word"] },
  { key: "x", desc: "Delete character under cursor", category: "clipboard", subcategory: "Delete (Cut)", keywords: ["delete", "character", "under", "cut"] },
  { key: "X", desc: "Delete character before cursor (backspace)", category: "clipboard", subcategory: "Delete (Cut)", keywords: ["delete", "character", "before", "backspace"] },

  // SEARCH & REPLACE
  { key: "/pattern", desc: "Search forward for 'pattern'", category: "search_replace", subcategory: "Search", keywords: ["search", "find", "forward", "pattern"] },
  { key: "?pattern", desc: "Search backward for 'pattern'", category: "search_replace", subcategory: "Search", keywords: ["search", "find", "backward", "pattern"] },
  { key: "\\", desc: "Escape/disable special meaning of search char", category: "search_replace", subcategory: "Regex Patterns", keywords: ["escape", "special", "literal"] },
  { key: "jo[ha]n", desc: "Match 'john' or 'joan' (brackets match char class)", category: "search_replace", subcategory: "Regex Patterns", keywords: ["class", "match", "optional", "brackets"] },
  { key: "*A", desc: "Match A, AA, AAA (star matches 0 or more)", category: "search_replace", subcategory: "Regex Patterns", keywords: ["wildcard", "multiple", "zero", "more", "star"] },
  { key: "x|y", desc: "Match x OR y", category: "search_replace", subcategory: "Regex Patterns", keywords: ["or", "either", "pipe", "alternative"] },
  { key: "r.d", desc: "Match 'rad', 'rod', 'rid' (. matches any single char)", category: "search_replace", subcategory: "Regex Patterns", keywords: ["dot", "wildcard", "single", "character"] },
  { key: "\\<the", desc: "Match word starting with 'the' (e.g. 'the', 'theater')", category: "search_replace", subcategory: "Regex Patterns", keywords: ["word", "boundary", "start"] },
  { key: "the\\>", desc: "Match word ending with 'the' (e.g. 'the', 'breathe')", category: "search_replace", subcategory: "Regex Patterns", keywords: ["word", "boundary", "end"] },
  { key: "\\<the\\>", desc: "Match the exact word 'the' only", category: "search_replace", subcategory: "Regex Patterns", keywords: ["exact", "word", "boundary", "match"] },
  { key: ":s/old/new", desc: "Replace next occurrence of 'old' with 'new' in current line", category: "search_replace", subcategory: "Substitute (Replace)", keywords: ["substitute", "replace", "line", "single"] },
  { key: ":s/old/new/g", desc: "Replace ALL occurrences of 'old' with 'new' in current line", category: "search_replace", subcategory: "Substitute (Replace)", keywords: ["substitute", "replace", "line", "global", "all"] },
  { key: ":%s/old/new/g", desc: "Replace ALL occurrences of 'old' with 'new' in entire file", category: "search_replace", subcategory: "Substitute (Replace)", keywords: ["substitute", "replace", "file", "global", "all"] },
  { key: ":%s/old/new/gc", desc: "Replace ALL with confirmation prompt for each match", category: "search_replace", subcategory: "Substitute (Replace)", keywords: ["substitute", "replace", "file", "confirm", "ask"] },
  { key: ":2,9s/x/y/gi", desc: "Replace x with y between lines 2 and 9, ignoring case", category: "search_replace", subcategory: "Substitute (Replace)", keywords: ["substitute", "replace", "range", "lines", "ignore", "case"] },
  { key: ":g/v/x/d", desc: "Delete lines containing/not containing string x", category: "search_replace", subcategory: "Substitute (Replace)", keywords: ["delete", "lines", "global", "filter", "match"] },

  // ADVANCED (Visual, Macros, Marks, Registers, Misc)
  { key: "v", desc: "Start character visual mode", category: "advanced", subcategory: "Visual Mode", keywords: ["visual", "select", "mode", "highlight"] },
  { key: "V", desc: "Start line visual mode", category: "advanced", subcategory: "Visual Mode", keywords: ["visual", "select", "mode", "line", "linewise"] },
  { key: "Ctrl + v", desc: "Start block visual mode", category: "advanced", subcategory: "Visual Mode", keywords: ["visual", "select", "mode", "block", "column", "ctrl-v"] },
  { key: "o", desc: "Move cursor to other end of visual selection", category: "advanced", subcategory: "Visual Mode", keywords: ["visual", "selection", "toggle", "end", "cursor"] },
  { key: "O", desc: "Move cursor to other corner of visual block", category: "advanced", subcategory: "Visual Mode", keywords: ["visual", "selection", "block", "corner"] },
  { key: "aw", desc: "Select a whole word (in visual mode or with operation)", category: "advanced", subcategory: "Visual Mode", keywords: ["select", "word", "around"] },
  { key: "ab or aB", desc: "Select a block containing parentheses () or braces {}", category: "advanced", subcategory: "Visual Mode", keywords: ["select", "block", "around", "braces", "parentheses"] },
  { key: "ib or iB", desc: "Select inner block of parentheses () or braces {}", category: "advanced", subcategory: "Visual Mode", keywords: ["select", "inner", "block", "braces", "parentheses"] },
  { key: "Esc", desc: "Exit visual, insert, or command mode", category: "advanced", subcategory: "Modes", keywords: ["exit", "clear", "cancel", "escape"] },
  { key: "qa", desc: "Record macro into register 'a' (press q to stop)", category: "advanced", subcategory: "Macros", keywords: ["record", "macro", "register", "action"] },
  { key: "q", desc: "Stop recording macro", category: "advanced", subcategory: "Macros", keywords: ["stop", "record", "macro"] },
  { key: "@a", desc: "Execute macro recorded in register 'a'", category: "advanced", subcategory: "Macros", keywords: ["run", "execute", "macro", "register"] },
  { key: "@@", desc: "Execute last executed macro", category: "advanced", subcategory: "Macros", keywords: ["run", "execute", "last", "macro", "repeat"] },
  { key: "mc", desc: "Set mark 'c' at current cursor position", category: "advanced", subcategory: "Marks", keywords: ["set", "mark", "location", "bookmark"] },
  { key: "`c", desc: "Jump to exact position of mark 'c'", category: "advanced", subcategory: "Marks", keywords: ["jump", "mark", "exact", "location", "backtick"] },
  { key: "'c", desc: "Jump to start of line containing mark 'c'", category: "advanced", subcategory: "Marks", keywords: ["jump", "mark", "line", "start"] },
  { key: "''", desc: "Jump back to previous cursor position before jump", category: "advanced", subcategory: "Marks", keywords: ["jump", "back", "previous", "history", "quotes"] },
  { key: ":marks", desc: "List all active marks", category: "advanced", subcategory: "Marks", keywords: ["list", "marks", "active", "show"] },
  { key: ":reg", desc: "List all registers and their contents", category: "advanced", subcategory: "Registers", keywords: ["list", "registers", "contents", "show"] },
  { key: "\"xy", desc: "Yank text into register 'x'", category: "advanced", subcategory: "Registers", keywords: ["yank", "copy", "register", "specific"] },
  { key: "\"xp", desc: "Paste text from register 'x'", category: "advanced", subcategory: "Registers", keywords: ["paste", "put", "register", "specific"] },
  { key: ":wq or ZZ", desc: "Write (save) file and quit", category: "advanced", subcategory: "Commands & Config", keywords: ["save", "write", "quit", "exit"] },
  { key: ":w!", desc: "Force write (save) file overriding protections", category: "advanced", subcategory: "Commands & Config", keywords: ["save", "write", "force", "overwrite"] },
  { key: ":q!", desc: "Quit without saving changes", category: "advanced", subcategory: "Commands & Config", keywords: ["quit", "discard", "exit", "force"] },
  { key: ":!command", desc: "Run a shell/UNIX command (e.g. :!ls)", category: "advanced", subcategory: "Commands & Config", keywords: ["shell", "terminal", "run", "command"] },
  { key: ":r file", desc: "Read file contents and insert below cursor", category: "advanced", subcategory: "Commands & Config", keywords: ["read", "insert", "file", "import"] },
  { key: ":set [all]", desc: "Show options set by user (or default options)", category: "advanced", subcategory: "Commands & Config", keywords: ["settings", "options", "configuration", "show"] },
  { key: ":set option", desc: "Enable 'option' (e.g. :set nu)", category: "advanced", subcategory: "Commands & Config", keywords: ["settings", "enable", "option", "toggle"] },
  { key: ":set option=val", desc: "Assign value to 'option' (e.g. :set tabstop=4)", category: "advanced", subcategory: "Commands & Config", keywords: ["settings", "assign", "value", "option"] },
  { key: ":set nooption", desc: "Disable 'option' (e.g. :set nonu)", category: "advanced", subcategory: "Commands & Config", keywords: ["settings", "disable", "option", "toggle"] },

  // CUSTOM & PLUGIN SHORTCUTS
  { key: "Space f", desc: "Find Files (fuzzy search by name)", category: "advanced", subcategory: "Plugin & Config", keywords: ["find", "files", "fuzzy", "picker", "snacks", "space"] },
  { key: "Space s", desc: "Live Grep across codebase (press Ctrl+q to send matches to Quickfix)", category: "advanced", subcategory: "Plugin & Config", keywords: ["grep", "search", "live", "codebase", "snacks", "space"] },
  { key: "Space se", desc: "Grep by file extension (prompts for extension e.g. vhd, py, ts)", category: "advanced", subcategory: "Plugin & Config", keywords: ["grep", "extension", "vhd", "filter", "space"] },
  { key: "Space sr", desc: "Search & Replace all Quickfix matches (:cfdo %s/old/new/g | update)", category: "advanced", subcategory: "Plugin & Config", keywords: ["replace", "find", "quickfix", "cfdo", "substitute", "space"] },
  { key: "Space q", desc: "Toggle Quickfix window open/close", category: "advanced", subcategory: "Plugin & Config", keywords: ["quickfix", "toggle", "window", "copen", "cclose", "space"] },
  { key: "Ctrl + q", desc: "Send search results from Telescope / Snacks picker to Quickfix list", category: "advanced", subcategory: "Plugin & Config", keywords: ["quickfix", "send", "telescope", "snacks", "ctrl-q"] },
  { key: "Space b", desc: "Switch active buffers", category: "advanced", subcategory: "Plugin & Config", keywords: ["buffers", "switch", "open", "snacks", "space"] },
  { key: "Space e", desc: "File Explorer (Oil.nvim buffer tree - v for vsplit, - for split)", category: "advanced", subcategory: "Plugin & Config", keywords: ["file", "explorer", "oil", "tree", "split", "space"] },
  { key: "Space g", desc: "Git Dashboard (Neogit status, staging, diffs, commits)", category: "advanced", subcategory: "Git", keywords: ["git", "neogit", "dashboard", "status", "commit", "space"] },
  { key: "Space gv", desc: "Open Neogit in side-by-side vertical split", category: "advanced", subcategory: "Git", keywords: ["git", "neogit", "vertical", "vsplit", "space"] },
  { key: "Space g-", desc: "Open Neogit in top/bottom horizontal split", category: "advanced", subcategory: "Git", keywords: ["git", "neogit", "horizontal", "split", "space"] },
  { key: "Space dt", desc: "Diff open split windows side-by-side (diffthis)", category: "advanced", subcategory: "Git & Diff", keywords: ["diff", "windows", "side-by-side", "compare", "space"] },
  { key: "Space do", desc: "Turn off window diffing mode (diffoff)", category: "advanced", subcategory: "Git & Diff", keywords: ["diff", "off", "windows", "stop", "space"] },
  { key: "do / dp", desc: "Diff Obtain (do - pull change) / Diff Put (dp - push change)", category: "advanced", subcategory: "Git & Diff", keywords: ["diff", "obtain", "put", "pull", "push", "merge"] },
  { key: "]c / [c", desc: "Jump to next (]c) or previous ([c) Git change hunk", category: "advanced", subcategory: "Git & Diff", keywords: ["git", "change", "hunk", "next", "prev", "jump"] },
  { key: "Space h", desc: "Preview single Git change diff in floating popup", category: "advanced", subcategory: "Git", keywords: ["git", "preview", "hunk", "diff", "popup", "space"] },
  { key: "Space hr", desc: "Reset / undo single Git change hunk", category: "advanced", subcategory: "Git", keywords: ["git", "reset", "undo", "hunk", "revert", "space"] },
  { key: "Space hw", desc: "Toggle ignore whitespace in Git diffs & gutters", category: "advanced", subcategory: "Git & Diff", keywords: ["git", "whitespace", "ignore", "toggle", "diff", "space"] },
  { key: "Space wc", desc: "Interactively create Git worktree & branch via Telescope", category: "advanced", subcategory: "Git Worktree", keywords: ["git", "worktree", "create", "branch", "telescope", "space"] },
  { key: "Space wm", desc: "Manage / Switch / Delete Git worktrees (Ctrl-d or d to delete)", category: "advanced", subcategory: "Git Worktree", keywords: ["git", "worktree", "manage", "switch", "delete", "space"] },
  { key: "Space um", desc: "Toggle VS Code-style code minimap on right side", category: "advanced", subcategory: "UI & Minimap", keywords: ["minimap", "code", "codewindow", "toggle", "vscode", "space"] },
  { key: "gt / gT", desc: "Cycle forward (gt) or backward (gT) through open tabs", category: "advanced", subcategory: "Tabs & Splits", keywords: ["tabs", "next", "prev", "cycle", "navigate"] },
  { key: "1gt .. 9gt", desc: "Jump directly to tab 1 through 9", category: "advanced", subcategory: "Tabs & Splits", keywords: ["tabs", "jump", "direct", "select"] },
  { key: "Ctrl + w + v / -", desc: "Split window vertically (v) or horizontally (-)", category: "advanced", subcategory: "Tabs & Splits", keywords: ["split", "window", "vertical", "horizontal"] },
  { key: "Ctrl + n", desc: "Multi-cursor select word under cursor & spawn next match", category: "advanced", subcategory: "Editing", keywords: ["multi-cursor", "select", "next", "ctrl-n"] },
  { key: "Ctrl + Shift + Down / Up", desc: "Spawn multi-cursor directly below / above", category: "advanced", subcategory: "Editing", keywords: ["multi-cursor", "down", "up", "spawn"] }
];
